テンプレートファイルの追加
LED-Camp/LED-Camp9 pull request #19
Opened 2021-06-13 06:47 UTC by tomohiro-iwa

2021-06-27 12:23 UTC, ken551 requested changes
動作確認したのですが，生成した`LEDTank.cpp`を食わせて，TankがWASDで動作することを確認しました．
headerのincludeについて，今はnot foundになってしまうのでそこの修正をお願いします．

動作確認していて，以下の二点が気になりました．あわせてご確認の程お願いします
（Templateからコードを生成するという，このPRの本質的なところには影響していないので，後回しにしてマージしても大丈夫です）
 
* Tankの動作がすごく遅い
* STOPの状態にするのが難しい（キーボードを意識して短く幼いと，１回押下したときに２回以上イベントが発生してしまう）

2021-06-27 12:23 UTC, ken551 commented on templates/cpp.template
> +#include "${u.name}.hpp"
生成されるヘッダファイルが `.h`形式なので，ここの拡張子は`.h`である必要があると思います
（同様に`main_sim.cpp`も`LEDTank.hpp`をinluceしようとしてるので修正する必要があると思います

2021-06-27 12:23 UTC, ken551 commented on templates/cpp.template
> +#include "${u.name}.hpp"
ヘッダファイルは`includesふぉるだ入れているので，`LEDTank.h`のincludeでも同様にincludeから指定してやる必要があると思います

2021-07-04 04:40 UTC, sho-hama commented on templates/cpp.template
> +#include "${u.name}.hpp"
それか、m2tで.hppで出力できないですかね？

2021-07-04 04:49 UTC, sho-hama commented on templates/cpp.template
> +#include "${u.name}.hpp"
一応LEDTank.hpp として出力できましたが、includesに入らないのでちょっと気持ち悪いですけど仕方ないですね

2021-07-04 05:05 UTC, sho-hama commented
反時計回りCCW->左回り
時計回りCW->右周り
という解釈だとするとテンプレートの左右逆な気がします。
あと出力10だと遅すぎるので100とかでいいと思います。

2021-07-10 02:59 UTC, tomohiro-iwa commented
以下修正しました。

テンプレートファイル名の修正
文字コードと改行コードを修正
検証用テンプレートの修正

includesファイル内にテンプレートを生成するのは、現在のm2tプラグインでは出来なさそうです。

> STOPの状態にするのが難しい（キーボードを意識して短く幼いと，１回押下したときに２回以上イベントが発生してしまう）

についてはキーイベント側の問題のため、このプルリクでは非対応とさせて下さい。

2021-07-10 03:48 UTC, ken551 commented
> 以下修正しました。
> 
> テンプレートファイル名の修正
> 文字コードと改行コードを修正
> 検証用テンプレートの修正
> 
> includesファイル内にテンプレートを生成するのは、現在のm2tプラグインでは出来なさそうです。
> 
> > STOPの状態にするのが難しい（キーボードを意識して短く幼いと，１回押下したときに２回以上イベントが発生してしまう）
> 
> についてはキーイベント側の問題のため、このプルリクでは非対応とさせて下さい。

これ思ったんですが，E_STOPに遷移するキーを追加してしまうのはどうでしょう？
このPRでやる必要はないと思いますが，リモートコントロール機能は参加者も使いうると思うので対応した方がいいんじゃないかなと思います

2021-07-10 05:07 UTC, tomohiro-iwa commented
@ken551 
たしか現状キーイベントは 4方向のみだったはずで、停止のイベント遷移を追加するにはイベントを付け足さないとならなくなると思います。
一度競技会をやってみるためにも早めにこのプルリクをマージしたいので、別PRでの対応とさせて下さい。

2021-07-10 05:15 UTC, ken551 approved these changes
LGTM

2021-07-10 05:16 UTC, merged